### PR TITLE
remove present? method and add logger to dependencies

### PR DESCRIPTION
**Pull request by kruszczynski**

### CODE REVIEW

**Comment by kubenstein** [comment]
:+1: 
Will merge tomorrow so other dynopoker community members have a chance to vote up/down.

**Comment by MagdaMalinowska** [comment]
:+1:

**Comment by fgeorgiew** [comment]
:+1:

**Comment by warkocz** [comment]
Good job! Waiting for more ;) :+1:

**Comment by Lackoftactics** [comment]
Awesome work. Keep the project going!

**Comment by korzonek** [comment]
Good Job! Keep on coding!

**Comment by Olgagr** [comment]
:+1:

**Comment by michal-samluk** [comment]
:+1:

**Comment by szymon-przybyl** [comment]
keep on opensourcin'! :ok_hand:

**Pull request merged**
